### ISSUE TITLE
values improperly converted to floats in csvkit?

### ISSUE THREAD

**Issue by derekeder** [datamade/ihs-charts#3]
Looks like some of the data is not being converted properly from XLSX to CSV. Note the values in these CSV files are being converted to floats that differ slightly:

https://github.com/datamade/ihs-charts/blob/master/state-of-rental-housing-2017/data/output/1-tenure.csv

https://github.com/datamade/ihs-charts/blob/master/state-of-rental-housing-2017/data/output/2-renters-income-total.csv

https://github.com/datamade/ihs-charts/blob/master/state-of-rental-housing-2017/data/output/3-renters-age-total.csv

Have we encountered this before with converting XLSX in csvkit before @jeancochrane @fgregg?

**Comment by evz** [comment]
Most csvkit tools so some kind of type inference. You can turn it off by passing the `--no-inference` flag. You might try that and see what happens.

**Comment by jeancochrane** [comment]
Yeah, I noticed this was happening while doing the conversions. It's a pain. Preliminary research indicates that .xls doesn't have an int type (only floats that are sometimes displayed like ints). Could be that the sheets are actually .xls. From the csvkit docs:

<img width="724" alt="screen shot 2017-03-23 at 9 37 54 am" src="https://cloud.githubusercontent.com/assets/14170650/24252825/8f25b730-0fac-11e7-818c-f9756832f618.png">

I decided not to do anything about it since it seemed like the frontend code was re-rounding the values appropriately before displaying them as charts. What do you think? Should I spend some time fixing it?

**Comment by derekeder** [comment]
@jeancochrane Geoff noticed that the numbers are off, which is how I discovered the issue. Let's try and fix it on the Make end. Maybe try the `--no-inference` flag?

**Comment by jeancochrane** [comment]
Cool – I'll get on it now.

**Comment by jeancochrane** [comment]
So it seems like csvkit won't be able to fix this: using `--no-inference` and specifying the filetype with the `-f` flag both return identical results to what we have using the Makefile in all three of the above cases. Bash isn't great with numerical types, so I'll probably have to hack together a processor to perform the rounding where appropriate.

I have, however, noticed that the JS rounding isn't working as expected either. If you compare [2-renters-income-total.csv](https://github.com/datamade/ihs-charts/blob/master/state-of-rental-housing-2017/data/output/2-renters-income-total.csv) to its chart (["Shifts in Renter Household By Income", third on the page](https://charts.housingstudies.org/state-of-rental-housing-2017/)) you'll notice that values are being truncated, not rounded, which is causing the script to display numbers that are 1 off from the Excel sheet when they end in .99999999. If rounded properly, the values in the CSV would match the display values in the Excel sheet.

Two options going forward, as I can see it: I can either write a processor to perform this rounding where appropriate in the Makefile, or tweak the JS to round properly. I'm leaning towards the former, since JS also isn't great with numerical types. Sound OK to you @derekeder?

**Comment by jeancochrane** [comment]
Added in the processor and fixed the CSVs linked above in [7c254c1](https://github.com/datamade/ihs-charts/commit/7c254c1d4ca85d9cdcd7931ba7d9a525d0cc310a). Those were the only float-related errors as far as I could tell, but let me know if Geoff finds any more!

**Comment by derekeder** [comment]
Looks good to me. Thx @jeancochrane!
